name: Build and Publish Extensions
    
on:
  push:
    tags:
      - 'ext-v*'
    branches:
      - master
  pull_request:
    branches:
      - master

jobs:
  build:
    runs-on: ubuntu-latest
    
    steps:
    - uses: actions/checkout@v4

    - name: Setup .NET
      uses: actions/setup-dotnet@v4
      with:
        dotnet-version: 8.0.x

    - name: Restore dependencies
      run: dotnet restore ./src/Apiand.Extensions/Apiand.Extensions.csproj

    - name: Build
      run: dotnet build ./src/Apiand.Extensions/Apiand.Extensions.csproj --configuration Release --no-restore

    - name: Test
      run: dotnet test ./src/Apiand.Extensions/Apiand.Extensions.csproj --configuration Release --no-build

    - name: Pack
      run: dotnet pack ./src/Apiand.Extensions/Apiand.Extensions.csproj --configuration Release --no-build --output ./artifacts

    - name: Upload artifacts
      uses: actions/upload-artifact@v4
      with:
        name: extensions-package
        path: ./artifacts/*.nupkg

  publish:
    needs: build
    if: startsWith(github.ref, 'refs/tags/ext-v')
    runs-on: ubuntu-latest

    steps:
    - name: Download artifact
      uses: actions/download-artifact@v3
      with:
        name: extensions-package
        path: ./artifacts

    - name: Setup .NET
      uses: actions/setup-dotnet@v3
      with:
        dotnet-version: 7.0.x

    - name: Publish to NuGet
      run: dotnet nuget push "./artifacts/*.nupkg" --api-key ${{ secrets.NUGET_API_KEY }} --source https://api.nuget.org/v3/index.json --skip-duplicate